### ISSUE TITLE
Wrong magnet uri

### ISSUE THREAD

**Issue by fpinzn** [feross/instant.io#24] opened 2015-03-29 00:04 UTC
Is always generating `magnet:?tr=wss%3A%2F%2Ftracker.webtorrent.io`

**Comment by feross** [comment] 2015-03-29 00:38
What are you doing to generate this magnet link?

**Comment by fpinzn** [comment] 2015-03-29 01:25
Upload a text file, click on download and copy the download file that appears under log.

**Comment by feross** [comment] 2015-04-01 22:53
Sorry, I can't reproduce this. Closing for now. Feel free to open a new issue if you're still experiencing this.

**Closed by feross** 2015-04-01 22:53 UTC
