### ISSUE TITLE
Config option for deploying to heroku

### ISSUE THREAD

**Issue by joshterrill** [feross/instant.io#82] opened 2015-08-21 22:46 UTC
What do you put for the IP address when deploying to heroku?

Edit: do you have to to use something like this? https://devcenter.heroku.com/articles/quotaguardstatic

**Comment by feross** [comment] 2015-08-22 00:29
Can you try setting it to `undefined`? I think you can just leave it out.

**Comment by feross** [comment] 2015-08-23 22:35
@alexlincoln - you deployed a mirror to Heroku, right? Can you help out @joshuaterrill here?

Also, weren't you going to add a one-click deploy to Heroku button to the readme?

**Comment by alexlincoln** [comment] 2015-08-24 06:52
@joshuaterrill you won't need to define an IP, simply using `undefined` should work. You do however need to add `process.env.PORT` to both protocols since Heroku dynamically assigns the app a port when its created. Here's an example of my config:

```javascript
exports.isProd = process.env.NODE_ENV === 'production'
exports.host = exports.isProd && '23.239.22.146' && !process.env.DYNO
exports.ports = {
  http: exports.isProd ? process.env.PORT || 80 : 9100,
  https: exports.isProd ? process.env.PORT || 443 : 9101
}
```
@feross Yep, I'm still planning on it I've just been fairly busy lately. I do need to tweak the configuration a bit more to make sure everything works as intended.

**Comment by joshuaterrill** [comment] 2015-08-25 21:21
Right on, thanks guys!

**Comment by joshuaterrill** [comment] 2015-08-25 21:34
I've tried to create a heroku instance of instant.io... I've created the config file as you instructed, ran npm install, created a proc file with npm start in it, then did heroku create and pushed my changes out. However I'm getting an application error. Here's the log file:
```
2015-08-25T21:26:56.046841+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-08-25T21:26:56.046706+00:00 app[web.1]: npm ERR!     npm owner ls instant.io
2015-08-25T21:26:56.049929+00:00 app[web.1]: 
2015-08-25T21:26:56.071845+00:00 app[web.1]: npm ERR! Linux 3.13.0-57-generic
2015-08-25T21:26:56.283394+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-08-25T21:26:56.282799+00:00 app[web.1]: 
2015-08-25T21:26:56.283513+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-08-25T21:26:57.023199+00:00 heroku[web.1]: State changed from starting to crashed
2015-08-25T21:26:57.009981+00:00 heroku[web.1]: Process exited with status 1
2015-08-25T21:27:31.369547+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=aqueous-earth-3943.herokuapp.com request_id=1f05b615-de41-466d-9436-0af1dd64a2d6 fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
2015-08-25T21:27:32.001172+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=aqueous-earth-3943.herokuapp.com request_id=717a189d-39b3-40c4-96cd-55f6886c5d02 fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
2015-08-25T21:28:05.103901+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=aqueous-earth-3943.herokuapp.com request_id=db2358b5-d426-4a0b-b1e4-9cfcff14973e fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
2015-08-25T21:28:05.631113+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=aqueous-earth-3943.herokuapp.com request_id=fcba3a14-a246-4da9-a6b9-04be5a8d1472 fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
2015-08-25T21:31:31.131966+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=aqueous-earth-3943.herokuapp.com request_id=7ea62cf3-cfd6-4db5-abf1-598de2790cec fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
2015-08-25T21:31:31.651874+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=aqueous-earth-3943.herokuapp.com request_id=8c5b7bfc-db17-4feb-8830-6774d9f24589 fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
2015-08-25T21:32:17.047658+00:00 heroku[slug-compiler]: Slug compilation started
2015-08-25T21:32:17.047689+00:00 heroku[slug-compiler]: Slug compilation finished
2015-08-25T21:32:16.981231+00:00 heroku[api]: Deploy 1c0211e by joshterrill.dev@gmail.com
2015-08-25T21:32:16.981419+00:00 heroku[api]: Release v4 created by joshterrill.dev@gmail.com
2015-08-25T21:32:18.480609+00:00 heroku[web.1]: State changed from crashed to starting
2015-08-25T21:32:22.003377+00:00 heroku[web.1]: Starting process with command `npm start`
2015-08-25T21:32:28.093756+00:00 app[web.1]: 
2015-08-25T21:32:28.093788+00:00 app[web.1]: 
2015-08-25T21:32:28.093784+00:00 app[web.1]: > instant.io@1.0.0 start /app
2015-08-25T21:32:28.093786+00:00 app[web.1]: > npm run build && node server
2015-08-25T21:32:31.828252+00:00 app[web.1]: 
2015-08-25T21:32:31.828260+00:00 app[web.1]: > instant.io@1.0.0 build /app
2015-08-25T21:32:31.828262+00:00 app[web.1]: > npm run build-css && npm run build-js
2015-08-25T21:32:31.828264+00:00 app[web.1]: 
2015-08-25T21:32:35.272694+00:00 app[web.1]: 
2015-08-25T21:32:35.272702+00:00 app[web.1]: > instant.io@1.0.0 build-css /app
2015-08-25T21:32:35.272705+00:00 app[web.1]: > stylus -u nib css/main.styl -o static/ -c
2015-08-25T21:32:35.272706+00:00 app[web.1]: 
2015-08-25T21:32:35.498040+00:00 app[web.1]: npm ERR! Linux 3.13.0-61-generic
2015-08-25T21:32:35.439293+00:00 app[web.1]: sh: 1: stylus: not found
2015-08-25T21:32:35.500999+00:00 app[web.1]: npm ERR! node v0.12.7
2015-08-25T21:32:35.501537+00:00 app[web.1]: npm ERR! npm  v2.11.3
2015-08-25T21:32:35.502195+00:00 app[web.1]: npm ERR! file sh
2015-08-25T21:32:35.502744+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-08-25T21:32:35.503266+00:00 app[web.1]: npm ERR! errno ENOENT
2015-08-25T21:32:35.503818+00:00 app[web.1]: npm ERR! syscall spawn
2015-08-25T21:32:35.504744+00:00 app[web.1]: npm ERR! instant.io@1.0.0 build-css: `stylus -u nib css/main.styl -o static/ -c`
2015-08-25T21:32:35.505179+00:00 app[web.1]: npm ERR! spawn ENOENT
2015-08-25T21:32:35.505646+00:00 app[web.1]: npm ERR! 
2015-08-25T21:32:35.506290+00:00 app[web.1]: npm ERR! Failed at the instant.io@1.0.0 build-css script 'stylus -u nib css/main.styl -o static/ -c'.
2015-08-25T21:32:35.507201+00:00 app[web.1]: npm ERR! not with npm itself.
2015-08-25T21:32:35.507606+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-08-25T21:32:35.507994+00:00 app[web.1]: npm ERR!     stylus -u nib css/main.styl -o static/ -c
2015-08-25T21:32:35.506772+00:00 app[web.1]: npm ERR! This is most likely a problem with the instant.io package,
2015-08-25T21:32:35.508373+00:00 app[web.1]: npm ERR! You can get their info via:
2015-08-25T21:32:35.508742+00:00 app[web.1]: npm ERR!     npm owner ls instant.io
2015-08-25T21:32:35.509120+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-08-25T21:32:35.513602+00:00 app[web.1]: 
2015-08-25T21:32:35.488703+00:00 app[web.1]: 
2015-08-25T21:32:35.499348+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "run" "build-css"
2015-08-25T21:32:35.514518+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-08-25T21:32:35.514909+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-08-25T21:32:35.543556+00:00 app[web.1]: 
2015-08-25T21:32:35.553345+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "run" "build"
2015-08-25T21:32:35.557912+00:00 app[web.1]: npm ERR! This is most likely a problem with the instant.io package,
2015-08-25T21:32:35.558280+00:00 app[web.1]: npm ERR! not with npm itself.
2015-08-25T21:32:35.558650+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-08-25T21:32:35.559051+00:00 app[web.1]: npm ERR!     npm run build-css && npm run build-js
2015-08-25T21:32:35.559411+00:00 app[web.1]: npm ERR! You can get their info via:
2015-08-25T21:32:35.559788+00:00 app[web.1]: npm ERR!     npm owner ls instant.io
2015-08-25T21:32:35.560185+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-08-25T21:32:35.564783+00:00 app[web.1]: 
2015-08-25T21:32:35.566167+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-08-25T21:32:35.738533+00:00 app[web.1]: npm ERR! Linux 3.13.0-61-generic
2015-08-25T21:32:35.552172+00:00 app[web.1]: npm ERR! Linux 3.13.0-61-generic
2015-08-25T21:32:35.554352+00:00 app[web.1]: npm ERR! node v0.12.7
2015-08-25T21:32:35.554832+00:00 app[web.1]: npm ERR! npm  v2.11.3
2015-08-25T21:32:35.555334+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-08-25T21:32:35.555862+00:00 app[web.1]: npm ERR! instant.io@1.0.0 build: `npm run build-css && npm run build-js`
2015-08-25T21:32:35.556352+00:00 app[web.1]: npm ERR! Exit status 1
2015-08-25T21:32:35.556777+00:00 app[web.1]: npm ERR! 
2015-08-25T21:32:35.557239+00:00 app[web.1]: npm ERR! Failed at the instant.io@1.0.0 build script 'npm run build-css && npm run build-js'.
2015-08-25T21:32:35.565641+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-08-25T21:32:35.707458+00:00 app[web.1]: 
2015-08-25T21:32:35.739443+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-08-25T21:32:35.739862+00:00 app[web.1]: npm ERR! node v0.12.7
2015-08-25T21:32:35.741606+00:00 app[web.1]: npm ERR! npm  v2.11.3
2015-08-25T21:32:35.742035+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-08-25T21:32:35.742450+00:00 app[web.1]: npm ERR! instant.io@1.0.0 start: `npm run build && node server`
2015-08-25T21:32:35.742917+00:00 app[web.1]: npm ERR! Exit status 1
2015-08-25T21:32:35.743280+00:00 app[web.1]: npm ERR! 
2015-08-25T21:32:35.743757+00:00 app[web.1]: npm ERR! Failed at the instant.io@1.0.0 start script 'npm run build && node server'.
2015-08-25T21:32:35.744762+00:00 app[web.1]: npm ERR! not with npm itself.
2015-08-25T21:32:35.762813+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-08-25T21:32:35.763079+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-08-25T21:32:35.744288+00:00 app[web.1]: npm ERR! This is most likely a problem with the instant.io package,
2015-08-25T21:32:35.745182+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-08-25T21:32:35.745503+00:00 app[web.1]: npm ERR!     npm run build && node server
2015-08-25T21:32:35.746018+00:00 app[web.1]: npm ERR! You can get their info via:
2015-08-25T21:32:35.746291+00:00 app[web.1]: npm ERR!     npm owner ls instant.io
2015-08-25T21:32:35.746632+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-08-25T21:32:35.754997+00:00 app[web.1]: 
2015-08-25T21:32:37.165322+00:00 heroku[web.1]: State changed from starting to crashed
2015-08-25T21:32:37.144421+00:00 heroku[web.1]: Process exited with status 1
2015-08-25T21:32:37.984392+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=aqueous-earth-3943.herokuapp.com request_id=b9b87a64-6117-4525-8f1a-82e79538f8b2 fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
2015-08-25T21:32:38.545207+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=aqueous-earth-3943.herokuapp.com request_id=f737f02e-1fd3-4fb1-946b-6c9765bb7937 fwd="198.207.150.8" dyno= connect= service= status=503 bytes=
```

**Comment by alexlincoln** [comment] 2015-08-25 23:06
@joshuaterrill It's basically missing necessary devDependencies to build the css and js. I'm still working on this issue, which is basically creating a custom buildpack to install `stylus` and `browserify` locally to build the assets when the app is deployed (basically something similar to this https://github.com/abhishekmunie/heroku-buildpack-webassets). 

For now, what I ended up doing was build the `static` assets on my end then pushed the directory up to Heroku. Once that's done, use `node server` instead of `npm start`. It's an ugly workaround. but it works fine.

**Comment by joshuaterrill** [comment] 2015-08-26 04:44
Why not just include that devdependency process inside the npm start process? Theoretically you could do that as well, right?

**Comment by alexlincoln** [comment] 2015-08-26 21:06
@joshuaterrill Alright so this is happening because Heroku doesn't have the supplied permissions to downgrade (basically to downgrade an process' privileges to that of a normal user if they were elevated). That's OK, since we don't actually need to downgrade on Heroku since the process is already fairly limited (to my knowledge). To fix this:

Go into `server/util.js` and change `if (process.platform === 'linux' && process.env.NODE_ENV === 'production')` to `if (process.platform === 'linux' && process.env.NODE_ENV === 'production' && !process.env.DYNO)`. As you can see we add `!process.env.DYNO`, a specific env variable that Heroku uses to identify your instance (i.e run.4118). This variable is used to detect whether or not we're using Heroku, so if we are to avoid downgrading since it's not necessary. In the future, that may or may not change so I'm looking at alternatives right now.

To my knowledge the only other issue you will likely encounter is an endless redirect issue due to forcing SSL requests. To fix this, it's fairly similar:

Go into `server/index.js` and find this line `if (config.isProd && req.protocol !== 'https'` and change that to `if (config.isProd && req.headers['x-forwarded-proto'] !== 'https')`. Why? Well since we don't own the domain and don't have the required cert/key pair needed, (although you could if you decide you want to use your own domain, I believe the SSL add-on is about $25/mo) we need to send non-https traffic to their load balancers. Instead of checking whether we're using `https` or not, we check the original protocol from the forwarded header sent by the load balancer (assuming its `http`), and redirect based on that. 

Once that's done, all requests should now be forced SSL now.
![2015-08-26-123121_1342x511_scrot](https://cloud.githubusercontent.com/assets/6338358/9506163/3fefa71e-4bfb-11e5-9b61-c972aa0e11b3.png)

I apologize if any of explanations are confusing at all. Keep me updated if you run into any other issues.

**Comment by feross** [comment] 2015-08-28 17:35
@alexlincoln If you want to submit these changes in a PR, I will merge them. It sounds like these changes will not affect non-heroku users.

Also, `server/util.js` is no more. The downgrade code is in it's own package now: https://npmjs.com/package/downgrade

**Comment by alexlincoln** [comment] 2015-08-29 22:59
@feross Sounds good, I'll get on that today

**Comment by feross** [comment] 2015-08-29 23:11
Nice, looking forward to it

**Comment by feross** [comment] 2016-07-27 03:45
@ghost PR still welcome, but I'm going to close this issue now.

**Closed by feross** 2016-07-27 03:45 UTC
