### ISSUE TITLE
Installation on Debian

### ISSUE THREAD

**Issue by sweety808** [feross/instant.io#117] opened 2016-08-19 07:44 UTC
Hi all,

I'm trying to start a clone of instant.io in my debian server but I got an erreur when I try to run it.

> stylus css/main.styl -o static/ -c

/usr/bin/env: node: No such file or directory

npm ERR! instant.io@1.0.0 build-css: `stylus css/main.styl -o static/ -c`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the instant.io@1.0.0 build-css script.
npm ERR! This is most likely a problem with the instant.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     stylus css/main.styl -o static/ -c
npm ERR! You can get their info via:
npm ERR!     npm owner ls instant.io
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.14.32-xxxx-grs-ipv6-64-vps
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-css"
npm ERR! cwd /home/instant.io
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

What is stylus ?

Merci ;)

**Comment by joshterrill** [comment] 2016-08-19 08:40
What were the commands you did to start it? Did you run `npm run build` before `npm start` to compile all the css and javascript files?

**Comment by feross** [comment] 2016-08-19 08:46
See http://stackoverflow.com/a/18130296/292185

Duplicate of https://github.com/feross/instant.io/issues/112

**Closed by feross** 2016-08-19 08:46 UTC

**Comment by sweety808** [comment] 2016-08-19 10:34
Yes it work 👍  
Thanks everyone
